### ISSUE TITLE
Rare critical crash

### ISSUE THREAD

**Issue by AlexGee17** [roytornado/RSLoadingView#7]
Hello! 

I think, you should consider either using optional with "loadingView" or apply some kind of nil
```
if loadingView != nil{
        loadingView.removeFromSuperview()
    }
```

In very rare cases, when you pop view controller without animation, while using "RSLoadingView" on both VCs your app can crash, because`loadingView.removeFromSuperView()` is called when loadingView is already nil.

**Comment by roytornado** [comment]
Thanks for comment.
Improved on 1.1.2
